### ISSUE TITLE
Every non-abstract Command class must be sealed

### ISSUE THREAD

**Issue by ironcev** [sharpenrocks/Sharpen#10]

**Comment by shubh07** [comment]
Hi Igor,

Could you please provide more details or perhaps an example on the same?

Thanks,
Shubham Bahuguna
Quovantis

**Comment by ironcev** [comment]
Hi Shubham,

commands are Sharpen's Visual Studio UI Commands that can be found in the [Commands folder](https://github.com/sharpenrocks/Sharpen/tree/master/src/Sharpen.VisualStudioExtension/Commands).

Precisely, those are the classes the derive directly or indirectly from [BaseSharpenCommand<TSharpenCommand>](https://github.com/sharpenrocks/Sharpen/blob/master/src/Sharpen.VisualStudioExtension/Commands/BaseSharpenCommand.cs).

They have to be internal and sealed like e.g. [AnalyzeSolutionCommand](https://github.com/sharpenrocks/Sharpen/blob/master/src/Sharpen.VisualStudioExtension/Commands/AnalyzeSolutionCommand.cs):

    internal sealed class AnalyzeSolutionCommand : BaseAnalyzeCommand<AnalyzeSolutionCommand>

This coded guideline checks if a non-abstract command class (means a class that derives directly or indirectly from `BaseSharpenCommand<TSharpenCommand>`) is sealed. This means, in this case, the Roslyn analyzer should show error and underline the whole class definition with a red line:

    internal class MySolutionCommand : BaseAnalyzeCommand<AnalyzeSolutionCommand>

In this case of course not because the class is abstract:

    internal abstract class MySolutionCommand : BaseAnalyzeCommand<AnalyzeSolutionCommand>

For additional info see the implementation of all the commands in the [Commands folder](https://github.com/sharpenrocks/Sharpen/tree/master/src/Sharpen.VisualStudioExtension/Commands).

For implementing a Roslyn analyzer that checks these [tutorials](https://github.com/ironcev/awesome-roslyn#tutorials).

Please keep in mind that the *Sharpen.CodedGuidelines* project does not exist at the moment. That project has to be created as well and added to the solution before you start working on this concrete analyzer.

Please let me know if this helps and if you need any additional info.

**Comment by ironcev** [comment]
And yes, thanks for taking a look at the issue :-) I'm looking forward to a pull request down the road ;-)

**Comment by ironcev** [comment]
See #7.
