### ISSUE TITLE
Every Command class must be internal

### ISSUE THREAD

**Issue by ironcev** [sharpenrocks/Sharpen#11]

**Comment by shubh07** [comment]
Hi Igor,

Could you please provide more details or perhaps an example on the same?

Thanks,
Shubham Bahuguna
Quovantis

**Comment by ironcev** [comment]
Hi Shubham

Please take a look at the description that I've just added to the Issue #10.

This one is essentially the same thing, just that it checks if the class is internal and #10 checks if it is sealed.

**Comment by ironcev** [comment]
See #7.
