### ISSUE TITLE
Displaying links for additional information on hoover

### ISSUE THREAD

**Issue by afrlan** [sharpenrocks/Sharpen#27]
Currently, when user hoovers over C# language version, "What is new in C# X.Y?" tip displays to the right of it. It would be an improvement if the tip would be displayed (as well) when hovering over tip displaying location.

The same is true for suggestions and "Learn more..." tip.

**Comment by ironcev** [comment]
I would go a step further and say - as soon as the user hoovers over the respective line, no matter how far from the text in that line, the link should appear. But of course, the best would be to try it and see is it is too anoying.

**Comment by ironcev** [comment]
@kurtanr Looks to me like something you would like to take a look at :-)

**Comment by tom-englert** [comment]
This is not achievable with the default template of the TreeViewItem, it would require a full redesign. 
I wonder if it's worth the effort...

**Comment by ironcev** [comment]
I fully trust @tom-englert's WPF expertiese and judgment. It took already a lot of effort to get the default template working. I would rather spend a full redesign effort on something else. Therefore I'll close the issue.
