### ISSUE TITLE
Process.Start(url) doesn't work in .Net Core 3.0

### ISSUE THREAD

**Issue by afrlan** [sharpenrocks/Sharpen#33]
While developing About dialog i came to the following issue:

I didn't pay much attention to Target framework when starting on the project and came to an interesting issue. Process.Start(url) in .Net Core 3.0 doesn't work (by design, it seems https://github.com/dotnet/corefx/issues/33714)

Process.Start(url) is used in Sharpen tool when opening links using CTRL key modifier.

Currently, this is not a bug but it could be overlooked if project's target framework changes.

**Comment by ironcev** [comment]
Thanks for pointing it out! VS extensions are at the moment written in .NET Classic and I am not aware of any plans for VS to support .NET Core. If the switch to Core ever happens or need to happen the fact that the Process.Start(url) doesn’t work will be the least of the trouble and effort. So I’ll close this issue but for sure thanks for pointing it out.
